### ISSUE TITLE
GS Issue

### ISSUE THREAD

**Issue by bankgodzilla** [mac2612/retroleap#100]
What type of system would you like to flash?

1. LF1000-Didj (Didj with EmeraldBoot)
2. LF1000 (Leapster Explorer)
3. LF2000 (Leapster GS, LeapPad 2, LeapPad Ultra XDI)
4. LF3000 (LeapPad 3, LeapPad Platinum)
Enter choice (1 - 4)
3

Waiting for 0 seconds, press a key to continue ...
Booting the Surgeon environment...
Writing CBF file.
CBF File Summary:
cbf_magic:      0x9abcdef0
cbf_version:    0x00000001
kernel_load:    0x00208000
kernel_jump:    0x00208000
size:           0x00640710
sum_crc:        0x9ad8d9e4
kernel_crc:     0xa1a8d1f0
Compressed:      True
Lines to write (should be a whole number) -
408
Traceback (most recent call last):
  File "mount.py", line 136, in find_device_id
    lines = str(self.sg_scan(), 'utf-8').split('\n')
TypeError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mount.py", line 232, in get_device_id_i
    return self._device_id or self.find_device_id()
  File "mount.py", line 174, in find_device_id
    self.error(e)
  File "mount.py", line 86, in error
    assert False, '%s' % e
AssertionError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "interface.py", line 51, in get_device_id
    return self._connection.get_device_id_i()
  File "mount.py", line 234, in get_device_id_i
    self.error(e)
  File "mount.py", line 86, in error
    assert False, '%s' % e
AssertionError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pager.py", line 105, in upload
    cmdl = '%s %s -b -s %s -n 2A 00 00 00 00 %s 00 00 20 00' % (self._sg_raw, self._mount_config.device_id, cbf.PACKET_SIZE, byte1)
  File "interface.py", line 53, in get_device_id
    self._connection.rerror(e)
  File "mount.py", line 89, in rerror
    assert False, 'Mount Error: %s' % e
AssertionError: Mount Error: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
  File "boot_surgeon.py", line 16, in do_surgeon_boot
  File "pager.py", line 124, in upload
    self.rerror(e)
  File "pager.py", line 66, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: Mount Error: decoding str is not supported
[16624] Failed to execute script 'boot_surgeon' due to unhandled exception!
Done! Waiting for Surgeon to come up...

Waiting for  0 seconds, press a key to continue ...
Done!
ssh: connect to host 169.254.8.1 port 22: Unknown error
ssh: connect to host 169.254.8.1 port 22: Unknown error
ssh: connect to host 169.254.8.1 port 22: Unknown error
"Detected Kernel partition= RFS Partition="

"Flashing the kernel...(lf2000_uImage)
ssh: connect to host 169.254.8.1 port 22: Unknown error
ssh: connect to host 169.254.8.1 port 22: Unknown error
The process tried to write to a nonexistent pipe.
Done flashing the kernel!
Flashing the root filesystem...
ssh: connect to host 169.254.8.1 port 22: Unknown error
ssh: connect to host 169.254.8.1 port 22: Unknown error

Waiting for 0 seconds, press a key to continue ...
ssh: connect to host 169.254.8.1 port 22: Unknown error

Waiting for 0 seconds, press a key to continue ...
ssh: connect to host 169.254.8.1 port 22: Unknown error
Writing rootfs image...
ssh: connect to host 169.254.8.1 port 22: Unknown error
The process tried to write to a nonexistent pipe.
ssh: connect to host 169.254.8.1 port 22: Unknown error
ssh: connect to host 169.254.8.1 port 22: Unknown error

Waiting for 0 seconds, press a key to continue ...

Done flashing the root filesystem!
Do you want to format the roms partition? (You should do this on the first flash of retroleap) (y/n):

**Comment by bankgodzilla** [comment]
Nevermind
