### ISSUE TITLE
root@169.254.8.1 password : when flashing

### ISSUE THREAD

**Issue by pa2ngehe** [mac2612/retroleap#32]
i facing "root@169.254.8.1's password :" when flashing my leapster explorer, and no button on keyboard can be press except the enter key.
first attempt was "'ssh' is not recognized as an internal or external command, operable program or batch file." popped, using sshflash-win from  @andymcca

Then i used OpenSSH from @bagajjal [https://github.com/PowerShell/Win32-OpenSSH], and put the required files to do SSH, in the folder sshflash-win.v0,2,alpha that @andymcca forked, but all i got when in state start to flashing is 

> root@169.254.8.1's password :

am i did something wrong? i try to WinSCP and submit id.rsa key to that protocol, somehow i can log into those leapster explorer's folder.

I realy new into linux environment (just did a couple time on Retropie, Batocera.linux on OrangePiPC).

**Comment by andymcca** [comment]
You need to use OpenSSH 8.1 or below on Windows, later versions don't support the RSA key that Retroleap uses for establishing SSH connections.  I've updated the Readme and release notes on sshflash-win to reflect this.

**Comment by pa2ngehe** [comment]
> You need to use OpenSSH 8.1 or below on Windows, later versions don't support the RSA key that Retroleap uses for establishing SSH connections. I've updated the Readme and release notes on sshflash-win to reflect this.

Thank's for your respond...

Did you mean OpenSSH 8.1 is for version, or it's mean Windows 8.1 (below)?, because i'm using Win10 and did not found OpenSSH in additional windows apps on setting.

If it's mean specific version of OpenSSH, where i can get that, can you provide the link?.

off topics :
until now, i can't find the leapfrog connect for this Leapster Explorer, even on their official web. I think they decide to put these to EOL state (Leapster GS also), and erased from their roadmap supports.

If something bed happen while flashing in progress, i can revert / re-install the stock FW because i didn't have leapfrog connect right?

Thank's for your kindness, and i will check your readme's update after this.

**Comment by pa2ngehe** [comment]
> You need to use OpenSSH 8.1 or below on Windows, later versions don't support the RSA key that Retroleap uses for establishing SSH connections. I've updated the Readme and release notes on sshflash-win to reflect this.

UPDATE PROGRESS : 

Flashing is SUCCESS.... (wink...wink)
now i'm going to try adding RETROARCH into it, since it's similar with gmenu2x on my CFW miyoo, wish it can work.

Thank's for your advise.

ps: still finding working leapfrog connect for this Leapster Explorer....

**Comment by andymcca** [comment]
Good to hear - we are testing Retroarch for the Explorer with latest Retroleap builds as mac and I  fixed some of the issues with it.  Try building Retroleap from latest repo commit and you should have Retroarch as an app in gmenunx

**Comment by pa2ngehe** [comment]
> Good to hear - we are testing Retroarch for the Explorer with latest Retroleap builds as mac and I fixed some of the issues with it. Try building Retroleap from latest repo commit and you should have Retroarch as an app in gmenunx

is that mean Retroleap will come to 2.1 ver? if you guys need a person to test it out, i'm in. Maybe beta tester (LF1000) before it throw into Final release, give me the package that mac & you already added the RA into gmenux, i failed try to adding RA as addition with the sameway like MiyooCFW methods (folder structures, and libs is totaly different), but .so (ext) i'm familiar on RA, i don't know where's to put it.

any way, you guys did a great jobs, and i want to be part of the team if needed. The people's respond also amazing when i throw my succedd Leapster Explorer turn into emulator device on emu group on FB.

Thank's, i'll wait for you guys respond.
will close this issue, and make another if it any.

**Comment by andymcca** [comment]
RetroArch for the Explorer (Add-on for current version of Retroleap) -
https://github.com/andymcca/retroleap/releases/tag/retroarch-v1.13.0-for-retroleap

**Comment by pa2ngehe** [comment]
> RetroArch for the Explorer (Add-on for current version of Retroleap) - https://github.com/andymcca/retroleap/releases/tag/retroarch-v1.13.0-for-retroleap

Hello there, i've already added the RA add-on, carefuly follow the readme file to put those assets into specified folders on my LF1000. The Retroarch icon is there (sections-emulators), but when i executed it just show "Launching Retroach", and it got freeze, and i have to detached battery to restart it. I double check the folders & files is just same like distributions mention on readme.

Did i made something wrong?
and....how can i adjust the overclock setup?

Thank's, will follow if it's any progress.

**Comment by andymcca** [comment]
Hi,
For info - I've just updated the add-on zip file with an extra core (Fuse ZX Spectrum), a few changes to the instructions and a change in the configs (alsathread audio instead of alsa).  I've also rebuilt the retroarch executable.

Your freeze problem above may be related to the overclock - on your PC, use Notepad (or similar) to edit the 'retroarch' file in the gmenunx folder, and try reducing the clock speed down from 532 to 500 and see if that helps?

Thanks
Andy

**Comment by andymcca** [comment]
Hi, I'll open this as an issue over on my fork - please continue conversation over there.

**Comment by pa2ngehe** [comment]
Hello Andy,

Changing the clock speed down to 500 is work.... Since i only had Leapster Explorer, i've got to changed clock speed of @mac2612 's default PocketSNES clock speed also.

Think i've noticed when playing 2 cores you provided is :

1. i need to remap the buttons in every games tittle, seems it not configured properly (both gpSP and QuickNES).
if there's global configuration to remapping button layout to each specifics core, and will apply to the all games on that core will be great.
Here for example is my gpSP buttons layout :
RA button targets -> LF1000 buttons
A          -> B
B          -> A
Select   -> Pause
Start     -> Hint
L          -> L
R          -> R
The rest is similar like OG GBA buttons (d-pad).

Every i quit RA, i need to remapping again games that i already remapped, even though i saved the .rmp files (games .rmp, or cores .rmp), no matter i loaded those .rmp files is not changing the buttons layout, it's quit hassle to do this.
anyway the alsathread is did great job.

2. QuickNES is also had this same issue.

Should we move to your specify thread?

Thank's in advance

**Comment by andymcca** [comment]
@pa2ngehe core remaps work ok for me?  Procedure is -

1. Load game
2. Go back to menu
3. Go to controls
4. Port 1 Controls -> Change to how you want it
5. Back to previous Menu -> Manage Remap files
6. Save Core Remap file
7. Go back to the game

I tested this and came out of RetroArch/went back in etc and settings saved for me.

**Comment by BullieCaSa** [comment]
Just dropping by to confirm that the Retroleap v2.0.0-alpha5 build is working great on Ubuntu 22.04.1 LTS.

**Comment by kieuphong** [comment]
> Just dropping by to confirm that the Retroleap v2.0.0-alpha5 build is working great on Ubuntu 22.04.1 LTS.

How did you make it work?  I tried the alpha6 version on 22.04.2 but it didnt work.  Actually none of this stuff work on linux for me. Only alpha4 works on windows that's it.  This is frustrating!

**Comment by kieuphong** [comment]
> > > Just dropping by to confirm that the Retroleap v2.0.0-alpha5 build is working great on Ubuntu 22.04.1 LTS.
> > 
> > 
> > How did you make it work? I tried the alpha6 version on 22.04.2 but it didnt work. Actually none of this stuff work on linux for me. Only alpha4 works on windows that's it. This is frustrating!
> 
> Where are you having issues? The one thing you may need to do that isn't in the readme is to install support for Python 2.x https://www.how2shout.com/linux/how-to-install-python-2-7-on-ubuntu-20-04-lts/

Thanks for trying to help.  I still get the following error after following your guide installing python 2

Enter choice (1 - 4)3
Booting the Surgeon environment...
Writing CBF file.
CBF File Summary:
kernel_crc:	0x1511a402
cbf_magic:	0x9abcdef0
cbf_version:	0x00000001
kernel_load:	0x00208000
kernel_jump:	0x00208000
sum_crc:	0x9ad8d1ec
size:		0x00640f18
Compressed: 	 True
Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
    do_surgeon_boot(sys.argv[1])
  File "boot_surgeon.py", line 16, in do_surgeon_boot
    pager_client.upload(path)
  File "/home/retroman/sshflash/pager.py", line 114, in upload
    self.rerror(e)
  File "/home/retroman/sshflash/pager.py", line 64, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: [Errno 2] No such file or directory
Done! Waiting for Surgeon to come up...Done!
ssh: connect to host 169.254.8.1 port 22: No route to host

**Comment by kieuphong** [comment]
OK.  Progress made!  So I deleted everything I downloaded before and redownloaded everything including sshflash and it worked with retroleap alpha 6! on Ubuntu 22.04.2 LTS. Was able to get the gmenunx and retroarch.  Question is how do I change the overclock value.  What is the file that contain this overclock parameter and where is it located?  Thanks!
