### ISSUE TITLE
AssertionError: Pager Error: Mount Error: Device not found.

### ISSUE THREAD

**Issue by Shibedev12** [mac2612/retroleap#39]
yes, yes, late to flash but im here, needin help.
logs state: _Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
    do_surgeon_boot(sys.argv[1])
  File "boot_surgeon.py", line 16, in do_surgeon_boot
    pager_client.upload(path)
  File "/home/shibe/sshflash/pager.py", line 114, in upload
    self.rerror(e)
  File "/home/shibe/sshflash/pager.py", line 64, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: Mount Error: Device not found.
Done! Waiting for Surgeon to come up...Done!_
then forever blinking cursor....
U-BOOT states that its state is timeout. board id is 0x0209
just a rego leapsterGS. idk what to do.

**Comment by Shibedev12** [comment]
instead did this instead of on wsl on actual linux, flashed now!
