### ISSUE TITLE
Leapster not connecting properly

### ISSUE THREAD

**Issue by Darkbubbz** [mac2612/retroleap#46]
Hi ive been trying to get mine to connect but am having quite the hard time.

This is me trying it on my windows computer with the current install. When i plug my unit in I cant seem to find the USB-EMM adaptor.

CBF File Summary:
cbf_magic:      0x9abcdef0
cbf_version:    0x00000001
kernel_load:    0x00100000
kernel_jump:    0x00100000
size:           0x00229318
sum_crc:        0x9a9e4dec
kernel_crc:     0x3fd3d2d7
Compressed:      True
Booting the Surgeon environment...
Writing CBF file.
CBF File Summary:
cbf_magic:      0x9abcdef0
cbf_version:    0x00000001
kernel_load:    0x00100000
kernel_jump:    0x00100000
size:           0x00553b2c
sum_crc:        0x9ae9e5e0
kernel_crc:     0x7d46b1cc
Compressed:      True
Lines to write (should be a whole number) -
344
Traceback (most recent call last):
  File "mount.py", line 136, in find_device_id
    lines = str(self.sg_scan(), 'utf-8').split('\n')
TypeError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mount.py", line 232, in get_device_id_i
    return self._device_id or self.find_device_id()
  File "mount.py", line 174, in find_device_id
    self.error(e)
  File "mount.py", line 86, in error
    assert False, '%s' % e
AssertionError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "interface.py", line 51, in get_device_id
    return self._connection.get_device_id_i()
  File "mount.py", line 234, in get_device_id_i
    self.error(e)
  File "mount.py", line 86, in error
    assert False, '%s' % e
AssertionError: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pager.py", line 105, in upload
    cmdl = '%s %s -b -s %s -n 2A 00 00 00 00 %s 00 00 20 00' % (self._sg_raw, self._mount_config.device_id, cbf.PACKET_SIZE, byte1)
  File "interface.py", line 53, in get_device_id
    self._connection.rerror(e)
  File "mount.py", line 89, in rerror
    assert False, 'Mount Error: %s' % e
AssertionError: Mount Error: decoding str is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
  File "boot_surgeon.py", line 16, in do_surgeon_boot
  File "pager.py", line 124, in upload
    self.rerror(e)
  File "pager.py", line 66, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: Mount Error: decoding str is not supported
[9808] Failed to execute script 'boot_surgeon' due to unhandled exception!
Done! Waiting for Surgeon to come up...

**Comment by andymcca** [comment]
You need to raise any issues for sshflash-win on its own github repo - https://github.com/andymcca/sshflash-win

Please check the known issue there for this error and also ensure you're following the YouTube guides for getting Retroleap on your device.

**Comment by Common-Leap** [comment]
ATTENTION 
THE SOLUTION TO THE FAILED NETWORK CONNECTION IS TO SWITCH FROM PYTHON 3 TO PYTHON 2
