### ISSUE TITLE
Issues winth LeapsterGS 

### ISSUE THREAD

**Issue by stoneman2221** [mac2612/retroleap#70]
Hello,

Not sure why the python is not being found or why the 'surgeon_tmp.cbf': No such file or directory.

Please help :)

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

`chris@KbunDJkitty:~/sshflash$ ./remote_flash.sh
Leapster flash utility - installs a custom OS on your leapster!

WARNING! This utility will ERASE the stock leapster OS and any other
data on the device. The device can be restored to stock settings using
the LeapFrog Connect app. Note that flashing your device will likely
VOID YOUR WARRANTY! Proceed at your own risk.

Please power off your leapster, hold the L + R shoulder buttons (LeapsterGS), 
or right arrow + home buttons (LeapPad2), and then press power.
You should see a screen with a green background.
Press enter when you're ready to continue.
----------------------------------------------------------------
What type of system would you like to flash?

1. LF1000-Didj (Didj with EmeraldBoot)
2. LF1000 (Leapster Explorer)
3. LF2000 (Leapster GS, LeapPad 2, LeapPad Ultra XDI)
4. LF3000 (LeapPad 3, LeapPad Platinum)
Enter choice (1 - 4)3
Booting the Surgeon environment...
Traceback (most recent call last):
  File "make_cbf.py", line 10, in <module>
    cbf.create(mem=sys.argv[1], opath=sys.argv[3], ipath=sys.argv[2])
  File "/home/chris/sshflash/cbf.py", line 142, in create
    error(e)
  File "/home/chris/sshflash/cbf.py", line 60, in error
    assert False, e
AssertionError: Path does not exist.
Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
    do_surgeon_boot(sys.argv[1])
  File "boot_surgeon.py", line 16, in do_surgeon_boot
    pager_client.upload(path)
  File "/home/chris/sshflash/pager.py", line 114, in upload
    self.rerror(e)
  File "/home/chris/sshflash/pager.py", line 64, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: Surgeon not found.
Done! Waiting for Surgeon to come up...rm: cannot remove 'surgeon_tmp.cbf': No such file or directory
Done!
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Detected Kernel partition= RFS Partition=
Flashing the kernel...ssh: connect to host 169.254.8.1 port 22: No route to host
cat: lf2000_uImage: No such file or directory
ssh: connect to host 169.254.8.1 port 22: No route to host
Done flashing the kernel!
Flashing the root filesystem...ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Writing rootfs image...
cat: lf2000_rootfs.tar.gz: No such file or directory
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
ssh: connect to host 169.254.8.1 port 22: No route to host
Done flashing the root filesystem!
Do you want to format the roms partition? (You should do this on the first flash of retroleap) (y/n)

Done! Rebooting the host.
`

**Comment by Common-Leap** [comment]
ATTENTION 
THE SOLUTION TO THE FAILED NETWORK CONNECTION IS TO SWITCH FROM PYTHON 3 TO PYTHON 2
