### ISSUE TITLE
AssertionError: Pager Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by verbes4** [mac2612/retroleap#78]
I'm on Arch Linux so I installed python2 from the AUR, don't know if that makes a difference. 

Leapster flash utility - installs a custom OS on your leapster!

WARNING! This utility will ERASE the stock leapster OS and any other
data on the device. The device can be restored to stock settings using
the LeapFrog Connect app. Note that flashing your device will likely
VOID YOUR WARRANTY! Proceed at your own risk.

Please power off your leapster, hold the L + R shoulder buttons (LeapsterGS), 
or right arrow + home buttons (LeapPad2), and then press power.
You should see a screen with a green background.
Press enter when you're ready to continue.
----------------------------------------------------------------
What type of system would you like to flash?

1. LF1000-Didj (Didj with EmeraldBoot)
2. LF1000 (Leapster Explorer)
3. LF2000 (Leapster GS, LeapPad 2, LeapPad Ultra XDI)
4. LF3000 (LeapPad 3, LeapPad Platinum)
Enter choice (1 - 4)2
Writing CBF file.
CBF File Summary:
kernel_crc:     0x61f6038f
cbf_magic:      0x9abcdef0
cbf_version:    0x00000001
kernel_load:    0x00100000
kernel_jump:    0x00100000
sum_crc:        0x9a9e4da8
size:           0x00229354
Compressed:      True
Booting the Surgeon environment...
Writing CBF file.
CBF File Summary:
kernel_crc:     0x94c521da
cbf_magic:      0x9abcdef0
cbf_version:    0x00000001
kernel_load:    0x00100000
kernel_jump:    0x00100000
sum_crc:        0x9aea2bc0
size:           0x0056f54c
Compressed:      True
Traceback (most recent call last):
  File "boot_surgeon.py", line 25, in <module>
    do_surgeon_boot(sys.argv[1])
  File "boot_surgeon.py", line 16, in do_surgeon_boot
    pager_client.upload(path)
  File "/home/josh/sshflash/pager.py", line 114, in upload
    self.rerror(e)
  File "/home/josh/sshflash/pager.py", line 64, in rerror
    assert False, 'Pager Error: %s' % e
AssertionError: Pager Error: [Errno 2] No such file or directory
Done! Waiting for Surgeon to come up...Done!

On the Leapster it just shows the "download leapfrog connect for your leapster explorer" error

**Comment by verbes4** [comment]
forgot to install sg3_utils
